### ISSUE TITLE
Router기본 설정

### ISSUE THREAD

**Issue by KIMHT98** [Gongkademy/Gongkademy_Admin_Front_#1]
이렇게 하는거 맞나요ㅎㅎ
기본적인 라우터 세팅 했습니다.

**Comment by mung96** [comment]
👍👍👍이렇게 이슈 열면 되고, 이제 템플릿 설정해놔서 양식 맞춰서 적으면 돼.
그리고 오른쪽에 Label, Project의 status도 설정해주면 돼.
